name: Integració Contínua

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codi
      uses: actions/checkout@v3
    
    - name: Configurar Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Instal·lar dependències
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-qt PySide6
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Executar proves amb pytest
      run: pytest --tb=short --disable-warnings
